---

  - name: Put actual virtualbox repository
    apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian trusty contrib'

  - name: add auth key
    apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc state=present

  - name: install virtualbox
    apt: update_cache=yes name={{item}} state=present
    with_items:
       - linux-headers-4.2.0-23-generic
       - virtualbox-5.0
